services:
  lr-fulltext-books:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./config.yml:/home/.server/config.yml
    depends_on:
      es:
        condition: service_started
  es:
    image: bitnami/elasticsearch:latest
    ports:
      - 9200:9200
    volumes:
      - ~/lr-es-data:/bitnami/elasticsearch/data
